pull_request_rules:
  - name: Automatic merge on scheduled PR
    conditions:
      - "check-success=^Build\sTest"
      - "check-success=^Integration\sTest"
      - "check-success=^Unit\sTest"
      - "check-success=^Verify-codegen"
      - "author=tom24d"
      - title~=(?i)scheduled
      - base=main
    actions:
      merge:
        method: squash
